apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-dep
  labels:
    app: voting-app
spec:
  replicas: 3
  selector:
    matchLabels:
      name: redis-pod
      app: voting-app
  template:
    metadata:
      name: redis-pod
      labels:
        name: redis-pod
        app: voting-app

    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
