apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-dep
  labels:
    app: voting-app
spec:
  replicas: 3
  selector:
    matchLabels:
      name: result-pod
      app: voting-app
  template:
    metadata:
      name: result-pod
      labels:
        name: result-pod
        app: voting-app

    spec:
      containers:
      - name: result-app
        image: dockersamples/examplevotingapp_result
        ports:
        - containerPort: 80
