apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-dep
  labels:
    app: voting-app
spec:
  replicas: 3
  selector:
    matchLabels:
      name: voting-pod
      app: voting-app
  template:
    metadata:
      name: voting-pod
      labels:
        name: voting-pod
        app: voting-app

    spec:
      containers:
      - name: voting-appp
        image: kodekloud/examplevotingapp_vote:v1
        ports:
        - containerPort: 80
