apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deploy
  labels:
    app: voting-app
spec:
  replicas: 3
  selector:
    matchLabels:
      name: worker-pod
      app: voting-app
  template:
    metadata:
      name: worker-pod
      labels:
        name: worker-pod
        app: voting-app

    spec:
      containers:
      - name: worker-app
        image: dockersamples/examplevotingapp_worker
